"""add source_url to indicators

Revision ID: 0ecbc35dc223
Revises: ff9519c618c0
Create Date: 2026-07-28 14:33:23.807540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ecbc35dc223'
down_revision: Union[str, Sequence[str], None] = 'ff9519c618c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'indicators',
        sa.Column('source_url', sa.String(length=512), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicators', 'source_url')
    # ### end Alembic commands ###
